### ISSUE TITLE
Card component image src tag does not point to correct image file

### ISSUE THREAD

**Issue by bowmanhost** [cblweb/semantic-ui-bootstrap#3]
"overview.html" line 1663 should read:
`<img src="images/avatar/big/steve.jpg">`

**Comment by cambyliverson** [comment]
Hi @bowmanhost,
line 1663 is `<div class="card-content">` , did you marked wrong line number?

---

Revise
Oh, I got it. That's no problem, it is just a sample image.

**Comment by bowmanhost** [comment]
I pulled the line number from WebStorm. May explain the discrepancy.

Thanks for creating a very useful theme!
